version: '3.1'
services:
  scaled-fhir-db-master:
    image: ${PG_IMAGE}
    container_name: scaled-fhir-db-master
    ports:
      - "${PGPORT_MASTER}:5432"
    volumes:
      - "./pgdata_master:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER:     "${PGUSER}"
      POSTGRES_PASSWORD: "${PGPASSWORD}"
      POSTGRES_DB:       "${PGDATABASE}"

  scaled-fhir-db-alfa:
    image: ${PG_IMAGE}
    container_name: scaled-fhir-db-alfa
    ports:
      - "${PGPORT_ALFA}:5432"
    volumes:
      - "./pgdata_alfa:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER:     "${PGUSER}"
      POSTGRES_PASSWORD: "${PGPASSWORD}"
      POSTGRES_DB:       "${PGDATABASE}"

  scaled-fhir-db-beta:
    image: ${PG_IMAGE}
    container_name: scaled-fhir-db-beta
    ports:
      - "${PGPORT_BETA}:5432"
    volumes:
      - "./pgdata_beta:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER:     "${PGUSER}"
      POSTGRES_PASSWORD: "${PGPASSWORD}"
      POSTGRES_DB:       "${PGDATABASE}"

  # scaled-fhir:
  #   image: "${IMG}"
  #   container_name: scaled-fhir
  #   environment:
  #     PGHOST_MASTER: "scaled-fhir-db-master"
  #     PGHOST_ALFA: "scaled-fhir-db-alfa"
  #     PGHOST_BETA: "scaled-fhir-db-beta"
  #     PGPORT: "5432"
  #     PGDATABASE: "${PGDATABASE}"
  #     PGUSER: "${PGUSER}"
  #     PGPASSWORD: "${PGPASSWORD}"
  #   ports:
  #     - 8080:8887
  #   depends_on:
  #     - scaled-fhir-db-master
  #     - scaled-fhir-db-alfa
  #     - scaled-fhir-db-beta
